use std::env::var;
use std::fs;
use std::path::Path;

use heck::AsUpperCamelCase;
use mavinspect::protocol::{Dialect, Protocol};
use mavinspect::Inspector;
use mavspec::rust::r#gen::{Generator, GeneratorParams};

const DIALECT: &str = "rapid";

fn main() {
    let sources = [
        "./message_definitions/standard",
        "./message_definitions/extra",
    ];
    let out_dir = var("OUT_DIR").unwrap();
    let destination = Path::new(&out_dir).join("mavlink");

    // Parse XML once. We reuse the same protocol for mavspec's codegen and for emitting the From
    // impls that mavspec skips on inherited messages.
    let protocol = Inspector::builder()
        .set_sources(&sources)
        .build()
        .unwrap()
        .parse()
        .unwrap();

    generate_inherited_from_impls(&out_dir, &protocol);

    // Use Generator directly (rather than BuildHelper) so we can opt into the
    // `metadata` flag, which adds the `value()` / `name()` / `entries()` methods
    // on generated enums. nadir's MessageExt macro relies on `.value()`.
    Generator::new(
        protocol,
        &destination,
        GeneratorParams {
            metadata: true,
            ..Default::default()
        },
    )
    .generate()
    .unwrap();
}

// mavspec emits `impl From<Msg> for Rapid` only for messages it generates as a native struct in
// the rapid module. Inherited messages get a `pub type` re-export and no conversion. We mirror
// mavspec's own inheritance decision (`generator.rs::message_inherited_from`) against the parsed
// protocol and emit the missing impls, so callers can build `Rapid` via `.into()` on any message
// with no hand-written impl per type.
fn generate_inherited_from_impls(out_dir: &str, protocol: &Protocol) {
    let rapid = protocol
        .get_dialect_by_canonical_name(DIALECT)
        .expect("rapid dialect missing from parsed protocol");

    let mut out = String::from("// Generated by build.rs. Do not edit.\n");
    for message in rapid.messages() {
        if !is_inherited(message, rapid, protocol) {
            continue;
        }
        let variant = AsUpperCamelCase(message.name()).to_string();
        out.push_str(&format!(
            "impl From<rapid::messages::{v}> for Rapid {{\n    fn from(msg: rapid::messages::{v}) -> Self {{ Rapid::{v}(msg) }}\n}}\n",
            v = variant,
        ));
    }

    fs::write(Path::new(out_dir).join("rapid_from_impls.rs"), out).unwrap();
}

// A message is inherited into `dialect` (and so gets no From impl from mavspec) iff it was
// defined in a parent and its fingerprint there still matches the one seen from `dialect`.
// This mirrors `mavspec_rust_gen::generator::Generator::message_inherited_from`.
fn is_inherited(
    msg: &mavinspect::protocol::Message,
    dialect: &Dialect,
    protocol: &Protocol,
) -> bool {
    if msg.defined_in() == dialect.canonical_name() {
        return false;
    }
    let Some(origin) = protocol.get_dialect_by_canonical_name(msg.defined_in()) else {
        return false;
    };
    let Some(original) = origin.get_message_by_name(msg.name()) else {
        return false;
    };
    original.fingerprint_strict(Some(origin)) == msg.fingerprint_strict(Some(dialect))
}
